# Treinamento com interface de alto nível

## Importação das bibliotecas

In [1]:
# http://pytorch.org/
from os.path import exists

import torch

In [2]:
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.optim.lr_scheduler import StepLR

## Criação da rede

In [24]:
transform=transforms.Compose([
    transforms.Resize((32,32)),
    transforms.Grayscale(num_output_channels=1),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
    ])
dataset_train = datasets.CIFAR100('../data', train=True, download=True,transform=transform)
dataset_test = datasets.CIFAR100('../data', train=False, download=True,transform=transform)

Files already downloaded and verified
Files already downloaded and verified


In [5]:
len(dataset_test)

10000

In [6]:
len(dataset_train)

50000

In [7]:
aux = dataset_train[3]
x, y = aux
print(x.shape)
print(y)

torch.Size([1, 32, 32])
11


In [ ]:
y

1

In [25]:
input_size = 32*32
output_size = 100
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.layer1 = nn.Linear(input_size, 2048)
        self.layer2 = nn.Linear(2048, 4096)
        self.layer3 = nn.Linear(4096, 8192)
        self.layer4 = nn.Linear(8192, 8192)
        self.layer5 = nn.Linear(8192, 4096)
        self.layer6 = nn.Linear(4096, 2048)
        self.layer7 = nn.Linear(2048, 1024)
        self.layer8 = nn.Linear(1024, 512)
        self.layer9 = nn.Linear(512, 256)
        self.fc2 = nn.Linear(256, output_size)

    def forward(self, x):
        x = x.view(-1, input_size)
        x = self.layer1(x)
        x = F.relu(x)
        x = self.layer2(x)
        x = F.relu(x)
        x = self.layer3(x)
        x = F.relu(x)
        x = self.layer4(x)
        x = F.relu(x)
        x = self.layer5(x)
        x = F.relu(x)
        x = self.layer6(x)
        x = F.relu(x)
        x = self.layer7(x)
        x = F.relu(x)
        x = self.layer8(x)
        x = F.relu(x)
        x = self.layer9(x)
        x = F.relu(x)
        x = self.fc2(x)
        output = F.log_softmax(x, dim=1)
        return output

model = Net()

In [26]:
model

Net(
  (layer1): Linear(in_features=1024, out_features=2048, bias=True)
  (layer2): Linear(in_features=2048, out_features=4096, bias=True)
  (layer3): Linear(in_features=4096, out_features=8192, bias=True)
  (layer4): Linear(in_features=8192, out_features=8192, bias=True)
  (layer5): Linear(in_features=8192, out_features=4096, bias=True)
  (layer6): Linear(in_features=4096, out_features=2048, bias=True)
  (layer7): Linear(in_features=2048, out_features=1024, bias=True)
  (layer8): Linear(in_features=1024, out_features=512, bias=True)
  (layer9): Linear(in_features=512, out_features=256, bias=True)
  (fc2): Linear(in_features=256, out_features=100, bias=True)
)

## Treinamento

### Criando o objeto de treinamento

In [27]:
def train(log_interval, dry_run, model, device, train_loader, optimizer, epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.item()))
            if dry_run:
                break

In [28]:
def test(model, device, test_loader):
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            test_loss += F.nll_loss(output, target, reduction='sum').item()  # sum up batch loss
            pred = output.argmax(dim=1, keepdim=True)  # get the index of the max log-probability
            correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(test_loader.dataset)
    acc = 100. * correct / len(test_loader.dataset)
    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        acc))
    return acc

## Avaliação

In [ ]:
use_cuda = torch.cuda.is_available()
use_cuda

True

In [29]:
use_cuda = torch.cuda.is_available()

torch.manual_seed(1111)

device = torch.device("cuda" if use_cuda else "cpu")

train_kwargs = {'batch_size': 500}
test_kwargs = {'batch_size': 100}
if use_cuda:
    cuda_kwargs = {'num_workers': 1,
                    'pin_memory': True,
                    'shuffle': True}
    train_kwargs.update(cuda_kwargs)
    test_kwargs.update(cuda_kwargs)

train_loader = torch.utils.data.DataLoader(dataset_train,**train_kwargs)
test_loader = torch.utils.data.DataLoader(dataset_test, **test_kwargs)

model = Net().to(device)
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 8
scheduler = StepLR(optimizer, step_size=4, gamma=0.7)
best_acc = test(model, device, test_loader)
for epoch in range(1, epochs + 1):
    train(10, False, model, device, train_loader, optimizer, epoch)
    acc = test(model, device, test_loader)
    if acc > best_acc:
      torch.save(model.state_dict(), "cifar100_cnn.pt")
    scheduler.step()


Test set: Average loss: 4.6058, Accuracy: 100/10000 (1%)

Train Epoch: 1 [0/50000 (0%)]	Loss: 4.605468
Train Epoch: 1 [5000/50000 (10%)]	Loss: 4.606379
Train Epoch: 1 [10000/50000 (20%)]	Loss: 4.600414
Train Epoch: 1 [15000/50000 (30%)]	Loss: 4.572727
Train Epoch: 1 [20000/50000 (40%)]	Loss: 4.602988
Train Epoch: 1 [25000/50000 (50%)]	Loss: 4.595205
Train Epoch: 1 [30000/50000 (60%)]	Loss: 4.576916
Train Epoch: 1 [35000/50000 (70%)]	Loss: 4.461816
Train Epoch: 1 [40000/50000 (80%)]	Loss: 4.518792
Train Epoch: 1 [45000/50000 (90%)]	Loss: 4.524837

Test set: Average loss: 4.4973, Accuracy: 164/10000 (2%)

Train Epoch: 2 [0/50000 (0%)]	Loss: 4.491110
Train Epoch: 2 [5000/50000 (10%)]	Loss: 4.522687
Train Epoch: 2 [10000/50000 (20%)]	Loss: 4.496088
Train Epoch: 2 [15000/50000 (30%)]	Loss: 4.495710
Train Epoch: 2 [20000/50000 (40%)]	Loss: 4.509337
Train Epoch: 2 [25000/50000 (50%)]	Loss: 4.503011
Train Epoch: 2 [30000/50000 (60%)]	Loss: 4.482284
Train Epoch: 2 [35000/50000 (70%)]	Loss: 4.5

In [ ]:
aux = torch.load("mnist_cnn.pt")

<ipython-input-19-cb91ad9ab067>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  aux = torch.load("mnist_cnn.pt")


In [ ]:
aux

OrderedDict([('layer1.weight',
              tensor([[-0.0003, -0.0271,  0.0240,  ...,  0.0353,  0.0151, -0.0153],
                      [-0.0208, -0.0123,  0.0298,  ...,  0.0074, -0.0148, -0.0048],
                      [ 0.0010, -0.0267, -0.0105,  ...,  0.0171,  0.0191,  0.0073],
                      ...,
                      [-0.0194,  0.0303,  0.0269,  ...,  0.0003,  0.0118, -0.0055],
                      [ 0.0055, -0.0117, -0.0062,  ..., -0.0226, -0.0015, -0.0182],
                      [ 0.0190, -0.0259, -0.0127,  ..., -0.0030,  0.0031, -0.0264]],
                     device='cuda:0')),
             ('layer1.bias',
              tensor([-0.0177, -0.0261, -0.0074,  ..., -0.0339, -0.0301,  0.0227],
                     device='cuda:0')),
             ('layer2.weight',
              tensor([[-0.0271, -0.0070, -0.0012,  ..., -0.0216,  0.0065, -0.0299],
                      [-0.0017,  0.0243,  0.0073,  ...,  0.0054, -0.0276,  0.0368],
                      [-0.0211, -0.0065,  0.00

In [ ]:
model.load_state_dict(aux)

<All keys matched successfully>